/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Alert: typeof import('./components/ui/alert').Alert
  const AlertDescription: typeof import('./components/ui/alert').AlertDescription
  const AlertTitle: typeof import('./components/ui/alert').AlertTitle
  const Article: typeof import('./components/ui/article').Article
  const Avatar: typeof import('./components/ui/avatar').Avatar
  const AvatarFallback: typeof import('./components/ui/avatar').AvatarFallback
  const AvatarImage: typeof import('./components/ui/avatar').AvatarImage
  const Badge: typeof import('./components/ui/badge').Badge
  const Button: typeof import('./components/ui/button').Button
  const Card: typeof import('./components/ui/card').Card
  const CardContent: typeof import('./components/ui/card').CardContent
  const CardDescription: typeof import('./components/ui/card').CardDescription
  const CardFooter: typeof import('./components/ui/card').CardFooter
  const CardHeader: typeof import('./components/ui/card').CardHeader
  const CardTitle: typeof import('./components/ui/card').CardTitle
  const Container: typeof import('./components/ui/container').Container
  const DeveloperSpeedComparison: typeof import('./components/ui/speed-comparison').DeveloperSpeedComparison
  const Dialog: typeof import('./components/ui/dialog').Dialog
  const DialogClose: typeof import('./components/ui/dialog').DialogClose
  const DialogContent: typeof import('./components/ui/dialog').DialogContent
  const DialogDescription: typeof import('./components/ui/dialog').DialogDescription
  const DialogFooter: typeof import('./components/ui/dialog').DialogFooter
  const DialogHeader: typeof import('./components/ui/dialog').DialogHeader
  const DialogOverlay: typeof import('./components/ui/dialog').DialogOverlay
  const DialogPortal: typeof import('./components/ui/dialog').DialogPortal
  const DialogTitle: typeof import('./components/ui/dialog').DialogTitle
  const DialogTrigger: typeof import('./components/ui/dialog').DialogTrigger
  const Grid: typeof import('./components/ui/grid').Grid
  const Hero: typeof import('./components/ui/hero').Hero
  const Input: typeof import('./components/ui/input').Input
  const Navbar: typeof import('./components/ui/navbar').Navbar
  const Progress: typeof import('./components/ui/progress').Progress
  const Section: typeof import('./components/ui/section').Section
  const Separator: typeof import('./components/ui/separator').Separator
  const Sidebar: typeof import('./components/ui/sidebar').Sidebar
  const Skeleton: typeof import('./components/ui/skeleton').Skeleton
  const SpeedComparison: typeof import('./components/ui/speed-comparison').SpeedComparison
  const Tabs: typeof import('./components/ui/tabs').Tabs
  const TabsContent: typeof import('./components/ui/tabs').TabsContent
  const TabsList: typeof import('./components/ui/tabs').TabsList
  const TabsTrigger: typeof import('./components/ui/tabs').TabsTrigger
  const badgeVariants: typeof import('./components/ui/badge').badgeVariants
  const buttonVariants: typeof import('./components/ui/button').buttonVariants
  const forwardRef: typeof import('react').forwardRef
  const heroVariants: typeof import('./components/ui/hero').heroVariants
  const useCallback: typeof import('react').useCallback
  const useEffect: typeof import('react').useEffect
  const useMemo: typeof import('react').useMemo
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
}
// for type re-export
declare global {
  // @ts-ignore
  export type { AlertProps } from './components/ui/alert'
  import('./components/ui/alert')
  // @ts-ignore
  export type { BadgeProps } from './components/ui/badge'
  import('./components/ui/badge')
  // @ts-ignore
  export type { ButtonProps } from './components/ui/button'
  import('./components/ui/button')
  // @ts-ignore
  export type { HeroProps } from './components/ui/hero'
  import('./components/ui/hero')
  // @ts-ignore
  export type { InputProps } from './components/ui/input'
  import('./components/ui/input')
  // @ts-ignore
  export type { NavItem } from './components/ui/navbar'
  import('./components/ui/navbar')
  // @ts-ignore
  export type { SidebarItem } from './components/ui/sidebar'
  import('./components/ui/sidebar')
}
